#spring:
#  application:
#    name: manage.web
#  servlet:
#    multipart:
#      max-file-size: 22MB # ???????????
#      max-request-size: 22MB
#  datasource:
#    druid:
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: 101423CEce
#      driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:

    #    db-test:
    #      jdbc-url: jdbc:mysql://localhost:3306/test
    #      username: root
    #      password: 101423CEce
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #      type: com.alibaba.druid.pool.DruidDataSource
    #    db-crm:
    #      url: jdbc:mysql://localhost:3306/crm
    #      username: root
    #      password: 101423CEce
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #      type: com.alibaba.druid.pool.DruidDataSource

    #    url: jdbc:mysql://localhost:3306/test
    #    username: root
    #    password: 101423CEce
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      datasource:
        data_check:
          url: jdbc:mysql://localhost:3306/data_check
          username: root
          password: yixinmysql
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
      primary: test
      # ?????
    druid:
      # ?????????????
      initial-size: 5
      # ??????????
      min-idle: 5
      # ?????????
      max-active: 20
      # ????????????????
      max-wait: 60000
      # ??????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
      test-while-idle: true
      # ?????????????testWhileIdel?????
      time-between-eviction-runs-millis: 60000
      # ????????????????????????????????????(??????????????)
      min-evictable-idle-time-millis: 30000
      # ??????????????sql ?????????(oracle?? select 1 from dual)
      validation-query: select 'x'
      # ????????validationQuery????????,???????,???true
      test-on-borrow: false
      # ????????validationQuery????????,???????,???true
      test-on-return: false
      # ????preparedStatement, ???PSCache,PSCache???????????????????oracle,?mysql??????
      pool-prepared-statements: false
      # ????????filters????????sql?????stat: ?????Slf4j:?????waLL: ??sqL??
      #      filters: stat,wall,slf4j
      # ???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
      max-pool-prepared-statement-per-connection-size: -1
      # ????DruidDataSource?????
      use-global-data-source-stat: true

      web-stat-filter:
        # ????StatFilter???true
        enabled: true
        # ??????
        url-pattern: /*
        # ???????
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        # ????StatViewServlet???true
        enabled: true
        # ?????/druid?????StatViewServlet
        url-pattern: /druid/*
        # ????????
        reset-enable: false
        # ?????????????????root
        login-username: druid
        login-password: druid
        # IP???
        allow: 127.0.0.1
        # IP??????????deny???allow?
        deny:

#    keepAlive: true

#    filter:
#      # sql??
#
#      stat:
#  #          enabled: true
#        db-type: mysql
#        log-slow-sql: true
#        slow-sql-millis: 2000
#        connection-stack-trace-enable: true
#        slow-sql-log-level: info
#        # ???
#      wall:
#        db-type: mysql
#        config:
#          delete-allow: false
#          drop-table-allow: false

server:
  port: 80
#debug: true

#  ???????? mapper ????????? .xml ???
#??: ?????????? XML ??? Mapper ??????? Mapper XML ???? SQL ???????????????? XML ??? Mapper ??????????
#??: ?? MyBatis-Plus ??????????????? Mapper XML ???????????????
#??: com.example.entity ??? com.example.entity ??????????? MyBatis ??????
#??: ??? Mapper XML ?????????????????????????????? XML ??? Mapper ???????????????????
mybatis-plus:
  global-config:
    db-config:
      #      ??id
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.example.entity